// Code generated by Sharkweb. DO NOT EDIT.

package modules

import (
	"log"

	"github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/core/module"
	Consultation "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/Consultation"
	appointment "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/appointment"
	auth "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/auth"
	clinic "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/clinic"
	doctor "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/doctor"
	medicalrecord "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/medicalrecord"
	notification "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/notification"
	patients "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/patients"
	prescription "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/prescription"
	queue "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/queue"
	schedule "github.com/Sharkweb-IT-Park/sharkweb-mvp-base/backend/modules/schedule"
	"github.com/gin-gonic/gin"
)

func LoadModules() []module.Module {
	return []module.Module{
		Consultation.NewModule(),
		appointment.NewModule(),
		auth.NewModule(),
		clinic.NewModule(),
		doctor.NewModule(),
		medicalrecord.NewModule(),
		notification.NewModule(),
		patients.NewModule(),
		prescription.NewModule(),
		queue.NewModule(),
		schedule.NewModule(),
	}
}

func RegisterModules(r *gin.Engine, ctx *module.ModuleContext) {

	api := r.Group("/api")

	for _, m := range LoadModules() {

		log.Println("🔌 Loading module:", m.Name())

		if err := m.Init(ctx); err != nil {
			log.Fatalf("❌ Failed to init module %s: %v", m.Name(), err)
		}

		group := api.Group("/" + m.Name())
		m.RegisterRoutes(group)
	}
}
